on: [push]

jobs:
  boman_scan:
    runs-on: ubuntu-latest
    name: Test Job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Install packages
        run: sudo pip install --extra-index-url https://test.pypi.org/simple/ boman-cli-uat==0.7
      - name: Run scan  
        run: sudo boman-cli -a run -u https://devapi.boman.ai/v2/
